CREATE TABLE IF NOT EXISTS order_support_cases (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reference VARCHAR(60) NOT NULL UNIQUE,
  order_request_id BIGINT UNSIGNED NOT NULL,
  case_type ENUM('cancellation','return') NOT NULL,
  status ENUM('open','reviewing','approved','declined','collection_scheduled','in_transit','received','resolved','closed') NOT NULL DEFAULT 'open',
  reason_category ENUM('changed_mind','incorrect_item','damaged','defective','late_delivery','duplicate_order','address_problem','supplier_unavailable','other') NOT NULL,
  reason_details TEXT NOT NULL,
  evidence_urls JSON NULL,
  supplier_return_reference VARCHAR(190) NULL,
  supplier_return_url VARCHAR(1500) NULL,
  return_courier_name VARCHAR(120) NULL,
  return_tracking_number VARCHAR(160) NULL,
  return_tracking_url VARCHAR(1500) NULL,
  resolution ENUM('pending','refund','replacement','repair','cancelled_without_charge','declined','other') NOT NULL DEFAULT 'pending',
  refund_amount DECIMAL(12,2) NULL,
  internal_notes TEXT NULL,
  opened_by_admin_id BIGINT UNSIGNED NULL,
  resolved_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (order_request_id) REFERENCES order_requests(id) ON DELETE CASCADE,
  FOREIGN KEY (opened_by_admin_id) REFERENCES admins(id) ON DELETE SET NULL,
  INDEX idx_order_support_cases (order_request_id, status, created_at)
);
