import { Edit3, ExternalLink, Link2, PackagePlus, RefreshCw, Save, Sparkles, Trash2, X } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import StatusPill from '../StatusPill';
import { money } from '../../data/products';
import { adminRequest } from '../../lib/api';
import { useFeedback } from '../FeedbackProvider';
import { recommendedSellingPrice } from '../../../shared/domain';

type AdminProduct = {
  id: number; title: string; brand: string; model: string; barcode: string | null; pack_size: string; category: string;
  description: string; specifications: Record<string, string> | string; selling_price: number; minimum_profit: number | null;
  estimated_customer_delivery_cost: number; delivery_time: string | null; item_weight_size: string | null; internal_review_notes: string | null;
  status: string; review_reason?: string | null; image_url: string | null; retailer?: string | null; source_url?: string | null; supplier_sku?: string | null;
  current_cost?: number | null; original_displayed_price?: number | null; supplier_delivery_cost?: number | null;
  promotion_start_at?: string | null; promotion_end_at?: string | null; promotion_end_provided?: boolean | number;
  promotion_terms?: string | null; quantity_limit?: string | null; stock_status?: string | null; last_checked_at?: string | null;
  source_confidence?: string | null; price_verified?: boolean | number; price_updated_at?: string | null; price_change_reason?: string | null;
  images?: { id?: number; url: string; alt_text?: string; sort_order: number }[];
};

const emptyProduct = {
  title: '', category: '', brand: '', model: '', barcode: '', packSize: '', description: '', imageUrls: '', specifications: '',
  retailer: '', sourceUrl: '', supplierSku: '', currentCost: '', originalDisplayedPrice: '', stockStatus: 'unknown', lastCheckedAt: '',
  promotionStartAt: '', promotionEndAt: '', promotionEndProvided: false, promotionTerms: '', quantityLimit: '',
  sellingPrice: '', minimumProfit: '0', status: 'draft', supplierDeliveryCost: '0', estimatedCustomerDeliveryCost: '0',
  deliveryTime: '', itemWeightSize: '', sourceConfidence: 'low', supplierPriceVerified: false, reviewNotes: '', priceUpdatedAt: '', priceChangeReason: '',
};
type ProductForm = typeof emptyProduct;
type ImageQuality = { width: number; height: number; error?: boolean };

const specificationsText = (value: AdminProduct['specifications']) => {
  let specs: Record<string, string> = {};
  try { specs = typeof value === 'string' ? JSON.parse(value || '{}') : value || {}; } catch { specs = {}; }
  return Object.entries(specs).map(([key, item]) => `${key}: ${item}`).join('\n');
};
const parseSpecifications = (text: string) => Object.fromEntries(text.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => { const separator = line.indexOf(':'); return separator < 1 ? [line, ''] : [line.slice(0, separator).trim(), line.slice(separator + 1).trim()]; }));
const dateInput = (value?: string | null) => value ? new Date(value).toISOString().slice(0, 16) : '';
const optionalNumber = (value: string) => value.trim() === '' ? null : Number(value);
const optionalDate = (value: string) => value ? new Date(value).toISOString() : null;
const textValue = (value: unknown) => value == null ? '' : String(value);
const parseImageUrls = (value: string) => [...new Set(value.split(/\r?\n/).map((item) => item.trim()).filter(Boolean))];
const blankReview = { exactProductMatch: false, supplierPriceChecked: false, stockChecked: false, promotionDatesChecked: false, imagesChecked: false, descriptionChecked: false };

export default function ProductManager({ onChanged, initialEditId, onInitialEditHandled }: { onChanged?: () => void; initialEditId?: number; onInitialEditHandled?: () => void }) {
  const { confirm, notify } = useFeedback();
  const [products, setProducts] = useState<AdminProduct[]>([]);
  const [editing, setEditing] = useState<AdminProduct | null>(null);
  const [form, setForm] = useState<ProductForm>(emptyProduct);
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [importing, setImporting] = useState(false);
  const [deletingId, setDeletingId] = useState<number | null>(null);
  const [message, setMessage] = useState('');
  const [imageQuality, setImageQuality] = useState<ImageQuality | null>(null);
  const [review, setReview] = useState(blankReview);
  const [standardMarkup, setStandardMarkup] = useState(7);
  const load = useCallback(async (showSuccess = false) => { setLoading(true); try { setProducts(await adminRequest<AdminProduct[]>('/products')); if (showSuccess) notify('The product list is up to date.', 'success', 'Products refreshed'); } catch (error) { notify(error instanceof Error ? error.message : 'Products could not be loaded', 'error'); } finally { setLoading(false); } }, [notify]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void adminRequest<{ standard_markup_percent: number }>('/pricing-settings').then((settings) => setStandardMarkup(Number(settings.standard_markup_percent))).catch(() => {}); }, []);
  useEffect(() => { setImageQuality(null); }, [form.imageUrls]);
  const field = <K extends keyof ProductForm>(key: K, value: ProductForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  const add = () => { setEditing(null); setForm(emptyProduct); setReview(blankReview); setMessage(''); setOpen(true); };
  const edit = useCallback((product: AdminProduct) => {
    setEditing(product);
    setForm({ title: product.title, category: product.category, brand: product.brand, model: product.model, barcode: product.barcode || '', packSize: product.pack_size, description: product.description, imageUrls: (product.images?.map((image) => image.url) || [product.image_url].filter(Boolean)).join('\n'), specifications: specificationsText(product.specifications), retailer: product.retailer || '', sourceUrl: product.source_url || '', supplierSku: product.supplier_sku || '', currentCost: textValue(product.current_cost), originalDisplayedPrice: textValue(product.original_displayed_price), stockStatus: product.stock_status || 'unknown', lastCheckedAt: dateInput(product.last_checked_at), promotionStartAt: dateInput(product.promotion_start_at), promotionEndAt: dateInput(product.promotion_end_at), promotionEndProvided: Boolean(product.promotion_end_provided), promotionTerms: product.promotion_terms || '', quantityLimit: product.quantity_limit || '', sellingPrice: String(product.selling_price), minimumProfit: textValue(product.minimum_profit ?? 0), status: product.status === 'published' ? 'pending_review' : product.status, supplierDeliveryCost: textValue(product.supplier_delivery_cost ?? 0), estimatedCustomerDeliveryCost: textValue(product.estimated_customer_delivery_cost ?? 0), deliveryTime: product.delivery_time || '', itemWeightSize: product.item_weight_size || '', sourceConfidence: product.source_confidence || 'low', supplierPriceVerified: Boolean(product.price_verified), reviewNotes: product.internal_review_notes || '', priceUpdatedAt: dateInput(product.price_updated_at), priceChangeReason: product.price_change_reason || '' });
    setReview(blankReview);
    setMessage(''); setOpen(true);
  }, []);
  useEffect(() => {
    if (!initialEditId || loading) return;
    const product = products.find((item) => item.id === initialEditId);
    if (product) edit(product);
    onInitialEditHandled?.();
  }, [edit, initialEditId, loading, onInitialEditHandled, products]);
  const estimatedProfit = useMemo(() => Number(form.sellingPrice || 0) - Number(form.currentCost || 0) - Number(form.supplierDeliveryCost || 0) - Number(form.estimatedCustomerDeliveryCost || 0), [form.sellingPrice, form.currentCost, form.supplierDeliveryCost, form.estimatedCustomerDeliveryCost]);
  const margin = Number(form.sellingPrice) > 0 ? estimatedProfit / Number(form.sellingPrice) * 100 : 0;
  const minimumProfit = Number(form.minimumProfit || 0);
  const recommended = Number(form.currentCost) > 0 ? recommendedSellingPrice({ cost: Number(form.currentCost), originalPrice: optionalNumber(form.originalDisplayedPrice), promotionEndAt: form.promotionEndAt || null }, standardMarkup) : null;
  const profitHealthy = estimatedProfit >= minimumProfit;
  const publishMissing = [!form.title && 'name', !form.category && 'category', parseImageUrls(form.imageUrls).length === 0 && 'product image', !form.model && !form.packSize && 'exact model or pack size', !form.sourceUrl && 'supplier URL', !Number(form.currentCost) && 'supplier price', !form.supplierPriceVerified && 'price verification', !form.lastCheckedAt && 'last checked time', !['in_stock', 'low_stock'].includes(form.stockStatus) && 'in-stock status'].filter(Boolean) as string[];

  const importFromUrl = async () => {
    if (!form.sourceUrl) { const warning = 'Paste a Game or Makro product URL first.'; setMessage(warning); notify(warning, 'warning'); return; }
    setImporting(true); setMessage('');
    try {
      const imported = await adminRequest<Record<string, unknown>>('/products/import-url', { method: 'POST', body: JSON.stringify({ url: form.sourceUrl }) });
      setForm((current) => ({ ...current, title: textValue(imported.title) || current.title, category: textValue(imported.category) || current.category, brand: textValue(imported.brand) || current.brand, model: textValue(imported.model) || current.model, barcode: textValue(imported.barcode) || current.barcode, packSize: textValue(imported.packSize) || current.packSize, description: textValue(imported.description) || current.description, imageUrls: Array.isArray(imported.imageUrls) ? imported.imageUrls.map(textValue).join('\n') : textValue(imported.imageUrl) || current.imageUrls, retailer: textValue(imported.retailer) || current.retailer, sourceUrl: textValue(imported.sourceUrl) || current.sourceUrl, supplierSku: textValue(imported.supplierSku) || current.supplierSku, currentCost: textValue(imported.currentCost) || current.currentCost, originalDisplayedPrice: textValue(imported.originalDisplayedPrice) || current.originalDisplayedPrice, stockStatus: textValue(imported.stockStatus) || current.stockStatus, lastCheckedAt: dateInput(textValue(imported.lastCheckedAt)) || current.lastCheckedAt, promotionStartAt: dateInput(textValue(imported.promotionStartAt)) || current.promotionStartAt, promotionEndAt: dateInput(textValue(imported.promotionEndAt)) || current.promotionEndAt, promotionTerms: textValue(imported.promotionTerms) || current.promotionTerms, quantityLimit: textValue(imported.quantityLimit) || current.quantityLimit, supplierDeliveryCost: textValue(imported.supplierDeliveryCost) || current.supplierDeliveryCost, sourceConfidence: textValue(imported.sourceConfidence) || current.sourceConfidence, supplierPriceVerified: false, priceUpdatedAt: dateInput(textValue(imported.priceUpdatedAt)) || current.priceUpdatedAt, priceChangeReason: textValue(imported.priceChangeReason) || current.priceChangeReason, reviewNotes: textValue(imported.reviewNotes) || current.reviewNotes }));
      const importedMessage = textValue(imported.importWarning) || 'Fields imported. Review and verify them before publishing.';
      setMessage(importedMessage); notify(importedMessage, 'success', 'Supplier details imported');
    } catch (error) { const errorMessage = error instanceof Error ? error.message : 'The product URL could not be imported'; setMessage(errorMessage); notify(errorMessage, 'error'); } finally { setImporting(false); }
  };

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (form.status === 'published' && (!Object.values(review).every(Boolean) || publishMissing.length)) { setMessage(`Complete every review check before publishing${publishMissing.length ? `: ${publishMissing.join(', ')}` : '.'}`); return; }
    const approved = await confirm({ title: editing ? 'Save product changes?' : 'Add this product?', message: editing ? `Update “${form.title}” with these product and supplier details? Published listings may return to review after material changes.` : `Create “${form.title}” as a ${form.status.replace('_', ' ')} listing?`, confirmLabel: editing ? 'Save changes' : 'Add product' });
    if (!approved) return;
    setSaving(true); setMessage('');
    const wantsPublish = form.status === 'published';
    const payload = { title: form.title, category: form.category, brand: form.brand, model: form.model, barcode: form.barcode || null, packSize: form.packSize, description: form.description, imageUrls: parseImageUrls(form.imageUrls), specifications: parseSpecifications(form.specifications), sellingPrice: Number(form.sellingPrice), minimumProfit: optionalNumber(form.minimumProfit), estimatedCustomerDeliveryCost: optionalNumber(form.estimatedCustomerDeliveryCost), deliveryTime: form.deliveryTime || null, itemWeightSize: form.itemWeightSize || null, reviewNotes: form.reviewNotes || null, status: wantsPublish ? 'pending_review' : form.status, supplier: { retailer: form.retailer || null, sourceUrl: form.sourceUrl || null, supplierSku: form.supplierSku || null, currentCost: optionalNumber(form.currentCost), originalDisplayedPrice: optionalNumber(form.originalDisplayedPrice), stockStatus: form.stockStatus, lastCheckedAt: optionalDate(form.lastCheckedAt), promotionStartAt: optionalDate(form.promotionStartAt), promotionEndAt: optionalDate(form.promotionEndAt), promotionEndProvided: Boolean(form.promotionEndAt) || form.promotionEndProvided, promotionTerms: form.promotionTerms || null, quantityLimit: form.quantityLimit || null, supplierDeliveryCost: optionalNumber(form.supplierDeliveryCost), sourceConfidence: form.sourceConfidence, supplierPriceVerified: form.supplierPriceVerified, priceUpdatedAt: optionalDate(form.priceUpdatedAt), priceChangeReason: form.priceChangeReason || null } };
    try {
      const saved = await adminRequest<{ id?: number }>(editing ? `/products/${editing.id}` : '/products', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(payload) });
      const productId = editing?.id || saved.id;
      if (wantsPublish && productId) await adminRequest(`/products/${productId}/review`, { method: 'PATCH', body: JSON.stringify({ status: 'published', sellingPrice: Number(form.sellingPrice), reviewReason: form.reviewNotes || null, checklist: review }) });
      setOpen(false); await load(); notify(wantsPublish ? 'Review recorded and product published.' : editing ? 'Product and supplier details updated.' : 'Product saved.', 'success', wantsPublish ? 'Review complete' : editing ? 'Product updated' : 'Product added'); onChanged?.();
    }
    catch (error) { const errorMessage = error instanceof Error ? error.message : 'Product could not be saved'; setMessage(errorMessage); notify(errorMessage, 'error'); } finally { setSaving(false); }
  };
  const deleteProduct = async (product: AdminProduct) => {
    const approved = await confirm({ title: 'Delete this product?', message: `“${product.title}” will be removed from the storefront and active product list. Its order and price history will be preserved for audit purposes.`, confirmLabel: 'Delete product', tone: 'danger' });
    if (!approved) return;
    setDeletingId(product.id);
    try { await adminRequest(`/products/${product.id}`, { method: 'DELETE' }); setProducts((current) => current.filter((item) => item.id !== product.id)); notify(`“${product.title}” was deleted from the active catalogue.`, 'success', 'Product deleted'); onChanged?.(); }
    catch (error) { notify(error instanceof Error ? error.message : 'Product could not be deleted', 'error'); }
    finally { setDeletingId(null); }
  };

  return <>
    <section className="admin-card table-card product-manager"><div className="card-heading"><div><p className="kicker">Catalogue and sourcing</p><h2>Products</h2></div><div className="product-actions"><button type="button" className="outline-button" disabled={loading} onClick={() => void load(true)}><RefreshCw /> {loading ? 'Refreshing…' : 'Refresh'}</button><button type="button" className="solid-button" onClick={add}><PackagePlus /> Add product</button></div></div>
      {loading ? <p className="table-loading">Loading products…</p> : <div className="data-table"><div className="table-head product-table-grid"><span>Product</span><span>Status / stock</span><span>Selling</span><span>Supplier cost</span><span>Est. profit</span><span>Source</span><span>Actions</span></div>{products.map((product) => { const profit = Number(product.selling_price) - Number(product.current_cost || 0) - Number(product.supplier_delivery_cost || 0) - Number(product.estimated_customer_delivery_cost || 0); return <div className="table-row product-table-grid" key={product.id}><span><i className="table-thumb">{product.brand?.[0] || 'P'}</i><b>{product.title}<small>{product.model || 'No model'} · {product.pack_size || 'No pack size'}</small></b></span><span><StatusPill status={product.status} /><small>{product.stock_status?.replaceAll('_', ' ') || 'Stock unknown'}{product.review_reason ? ` · ${product.review_reason}` : ''}</small></span><strong>{money(Number(product.selling_price))}</strong><span>{product.current_cost == null ? 'Not provided' : money(Number(product.current_cost))}</span><span className={profit <= 0 || profit < Number(product.minimum_profit ?? 0) ? 'profit-low' : 'profit-good'}>{money(profit)}</span><span>{product.retailer || 'No supplier'}<small>{product.last_checked_at ? `Checked ${new Date(product.last_checked_at).toLocaleString('en-ZA')}` : 'Never checked'}</small></span><span className="row-actions"><button type="button" title="Edit product" aria-label={`Edit ${product.title}`} onClick={() => edit(product)}><Edit3 /> Edit</button><button type="button" title="Delete product" aria-label={`Delete ${product.title}`} className="danger" disabled={deletingId === product.id} onClick={() => void deleteProduct(product)}><Trash2 /> {deletingId === product.id ? 'Deleting…' : 'Delete'}</button></span></div>; })}</div>}
      {!loading && products.length === 0 && <div className="account-empty"><PackagePlus /><h3>No active products</h3><p>Create the first catalogue draft to begin supplier review.</p></div>}
    </section>
    {open && <div className="product-modal-backdrop" role="presentation"><section className="product-modal product-workflow-modal" role="dialog" aria-modal="true" aria-labelledby="product-form-title"><header><div><p className="kicker">{editing ? 'Edit sourcing record' : 'New sourcing record'}</p><h2 id="product-form-title">{editing ? editing.title : 'Add a product'}</h2></div><button type="button" onClick={() => setOpen(false)} aria-label="Close product form"><X /></button></header><form onSubmit={submit}>
      <section className="url-importer"><div><Link2 /><label>Supplier product URL<input type="url" value={form.sourceUrl} onChange={(event) => field('sourceUrl', event.target.value)} placeholder="https://www.game.co.za/... or https://www.makro.co.za/..." /></label></div><button type="button" className="solid-button" disabled={importing} onClick={() => void importFromUrl()}><Sparkles /> {importing ? 'Reading listing…' : 'Add from URL'}</button><p>Imports public product metadata only. Always review the exact model, checkout price and stock.</p></section>
      <div className="workflow-section-heading"><span>1</span><div><h3>Product and listing</h3><p>Keep the core record short; save incomplete work as a draft.</p></div></div>
      <div className="product-form-grid core-product-grid"><label>Product name *<input value={form.title} onChange={(event) => field('title', event.target.value)} required minLength={3} /></label><label>Category *<input value={form.category} onChange={(event) => field('category', event.target.value)} required /></label><label>Brand<input value={form.brand} onChange={(event) => field('brand', event.target.value)} /></label><label>Exact model / SKU<input value={form.model} onChange={(event) => field('model', event.target.value)} /></label><label>Variant or pack size<input value={form.packSize} onChange={(event) => field('packSize', event.target.value)} placeholder="e.g. 96 pack" /></label><label>Your selling price (ZAR) *<input type="number" min="0.01" step="0.01" value={form.sellingPrice} onChange={(event) => field('sellingPrice', event.target.value)} required />{recommended && <small>Source rule: {money(recommended.sellingPrice)} ({recommended.promotionActive ? 'promotion, below normal source price' : `${standardMarkup}% regular markup`}) <button type="button" onClick={() => field('sellingPrice', recommended.sellingPrice.toFixed(2))}>Use price</button></small>}</label><label>Listing status<select value={form.status} onChange={(event) => field('status', event.target.value)}><option value="draft">Draft</option><option value="pending_review">Pending review</option><option value="published">Published</option><option value="paused">Paused</option></select></label><label>Minimum acceptable profit<input type="number" min="0" step="0.01" value={form.minimumProfit} onChange={(event) => field('minimumProfit', event.target.value)} /></label></div>
      <div className="workflow-section-heading"><span>2</span><div><h3>Supplier verification</h3><p>Required fields are enforced when the listing is published.</p></div></div>
      <div className="product-form-grid"><label>Store name<input value={form.retailer} onChange={(event) => field('retailer', event.target.value)} placeholder="Game or Makro" /></label><label>Supplier SKU<input value={form.supplierSku} onChange={(event) => field('supplierSku', event.target.value)} /></label><label>Current supplier price<input type="number" min="0" step="0.01" value={form.currentCost} onChange={(event) => field('currentCost', event.target.value)} /></label><label>Displayed regular price<input type="number" min="0" step="0.01" value={form.originalDisplayedPrice} onChange={(event) => field('originalDisplayedPrice', event.target.value)} /></label><label>Stock status<select value={form.stockStatus} onChange={(event) => field('stockStatus', event.target.value)}><option value="unknown">Unknown</option><option value="in_stock">In stock</option><option value="low_stock">Low stock</option><option value="out_of_stock">Out of stock</option></select></label><label>Last checked<input type="datetime-local" value={form.lastCheckedAt} onChange={(event) => field('lastCheckedAt', event.target.value)} /></label><label className="check-field full-field"><input type="checkbox" checked={form.supplierPriceVerified} onChange={(event) => field('supplierPriceVerified', event.target.checked)} /><span>I verified this price against the supplier listing or checkout.</span></label></div>
      <div className={profitHealthy ? 'profit-preview healthy' : 'profit-preview danger'}><div><span>Conservative estimated profit</span><strong>{money(estimatedProfit)}</strong></div><div><span>Estimated margin</span><strong>{margin.toFixed(1)}%</strong></div><p>{profitHealthy ? `Meets the ${money(minimumProfit)} minimum.` : `Below the ${money(minimumProfit)} minimum—raise the selling price or reduce costs.`} Cart delivery revenue and final costs are recalculated when an order is placed.</p></div>
      {form.status === 'published' && publishMissing.length > 0 && <p className="publish-warning">Before publishing, complete: {publishMissing.join(', ')}.</p>}
      <details className="workflow-details" open><summary>Images and product details</summary><div className="product-form-grid details-fields"><label>Barcode<input value={form.barcode} onChange={(event) => field('barcode', event.target.value)} /></label><label className="full-field">Product image URLs <span>(one image per line, first image is the cover)</span><textarea rows={5} value={form.imageUrls} onChange={(event) => field('imageUrls', event.target.value)} placeholder="https://.../front.jpg&#10;https://.../side.jpg" /></label>{parseImageUrls(form.imageUrls)[0] && <div className="image-quality full-field"><img src={parseImageUrls(form.imageUrls)[0]} alt="Primary product image quality preview" onLoad={(event) => setImageQuality({ width: event.currentTarget.naturalWidth, height: event.currentTarget.naturalHeight })} onError={() => setImageQuality({ width: 0, height: 0, error: true })} /><div><strong>{imageQuality?.error ? 'Image could not be loaded' : `${parseImageUrls(form.imageUrls).length} image${parseImageUrls(form.imageUrls).length === 1 ? '' : 's'} · ${imageQuality ? `${imageQuality.width} × ${imageQuality.height}` : 'checking cover…'}`}</strong><span className={imageQuality && !imageQuality.error && Math.min(imageQuality.width, imageQuality.height) >= 1000 ? 'quality-good' : 'quality-warning'}>Add every useful angle available on the supplier listing and keep the best image first.</span></div></div>}<label className="full-field">Short description<textarea rows={3} value={form.description} onChange={(event) => field('description', event.target.value)} /></label><label className="full-field">Specifications <span>(one “Name: Value” per line)</span><textarea rows={4} value={form.specifications} onChange={(event) => field('specifications', event.target.value)} /></label></div></details>
      {form.status === 'published' && <section className="review-checklist"><h3>Publication review</h3><p>Confirm each item. This review is saved to the product audit history.</p>{Object.entries({ exactProductMatch: 'Exact model and variant match the supplier', supplierPriceChecked: 'Supplier checkout price is current', stockChecked: 'Stock is currently available', promotionDatesChecked: 'Promotion dates and terms were checked', imagesChecked: 'All available useful product images were added', descriptionChecked: 'Description and specifications are accurate' }).map(([key, label]) => <label key={key}><input type="checkbox" checked={review[key as keyof typeof review]} onChange={(event) => setReview((current) => ({ ...current, [key]: event.target.checked }))} /> {label}</label>)}</section>}
      <details className="workflow-details"><summary>Promotion</summary><div className="product-form-grid details-fields"><label>Sale start date<input type="datetime-local" value={form.promotionStartAt} onChange={(event) => field('promotionStartAt', event.target.value)} /></label><label>Sale end date<input type="datetime-local" value={form.promotionEndAt} onChange={(event) => { field('promotionEndAt', event.target.value); if (event.target.value) field('promotionEndProvided', true); }} /></label><label className="check-field full-field"><input type="checkbox" checked={form.promotionEndProvided} onChange={(event) => field('promotionEndProvided', event.target.checked)} /><span>The supplier explicitly provided a sale end date. Leave unchecked when no date is provided.</span></label><label className="full-field">Promotion terms<textarea rows={3} value={form.promotionTerms} onChange={(event) => field('promotionTerms', event.target.value)} /></label><label>Quantity limit<input value={form.quantityLimit} onChange={(event) => field('quantityLimit', event.target.value)} placeholder="e.g. Maximum 2 per customer" /></label></div></details>
      <details className="workflow-details"><summary>Fulfilment</summary><div className="product-form-grid details-fields"><label>Supplier delivery cost<input type="number" min="0" step="0.01" value={form.supplierDeliveryCost} onChange={(event) => field('supplierDeliveryCost', event.target.value)} /></label><label>Estimated customer delivery cost<input type="number" min="0" step="0.01" value={form.estimatedCustomerDeliveryCost} onChange={(event) => field('estimatedCustomerDeliveryCost', event.target.value)} /></label><label>Delivery time<input value={form.deliveryTime} onChange={(event) => field('deliveryTime', event.target.value)} placeholder="e.g. 3–5 business days" /></label><label>Item weight or size<input value={form.itemWeightSize} onChange={(event) => field('itemWeightSize', event.target.value)} /></label></div></details>
      <details className="workflow-details"><summary>Tracking and internal notes</summary><div className="product-form-grid details-fields"><label>Source confidence<select value={form.sourceConfidence} onChange={(event) => field('sourceConfidence', event.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label>Last price update<input type="datetime-local" value={form.priceUpdatedAt} onChange={(event) => field('priceUpdatedAt', event.target.value)} /></label><label className="full-field">Reason for price change<input value={form.priceChangeReason} onChange={(event) => field('priceChangeReason', event.target.value)} /></label><label className="full-field">Internal review notes<textarea rows={4} value={form.reviewNotes} onChange={(event) => field('reviewNotes', event.target.value)} /></label></div></details>
      {message && <p className="form-error">{message}</p>}<div className="product-form-actions"><button type="button" className="outline-button" onClick={() => setOpen(false)}>Cancel</button>{form.sourceUrl && <a className="outline-button" href={form.sourceUrl} target="_blank" rel="noreferrer">Open supplier <ExternalLink /></a>}<button className="solid-button" disabled={saving}><Save /> {saving ? 'Saving…' : editing ? 'Save changes' : 'Save product'}</button></div>
    </form></section></div>}
  </>;
}
